schema_version = 3

[project]
uuid = "9ec5f921-b2c6-41db-8ffd-bea03b583741"
name = "releaseledger"

[ledgers.releaseledger.mounts.data]
storage = "project"

[ledgers.releaseledger.mounts.indexes]
storage = "cache"
