"""Project-local TOML configuration for releaseledger.

This module owns parsing, validating, and rendering ``.releaseledger.toml``.
Path resolution relative to the config file lives in
:mod:`releaseledger.storage.paths`; this module deliberately has no filesystem
discovery so it can be unit-tested against plain dicts.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - Python 3.10 fallback
    import tomli as tomllib  # type: ignore[import-not-found]

from releaseledger.errors import CODE_CONFIG_ERROR, CODE_USAGE_ERROR, LaunchError

__all__ = [
    "ALLOWED_CHANGELOG_KEYS",
    "ALLOWED_GIT_KEYS",
    "ALLOWED_LEDGER_KEYS",
    "ALLOWED_RELEASE_KEYS",
    "ALLOWED_TOP_LEVEL_KEYS",
    "CONFIG_VERSION",
    "DEFAULT_CHANGELOG",
    "DEFAULT_CHANGELOG_FOOTER",
    "DEFAULT_CHANGELOG_TEMPLATE_BODY",
    "DEFAULT_KEEPACHANGELOG_TEMPLATE_BODY",
    "DEFAULT_LEDGER_CODE",
    "DEFAULT_LEDGER_NAME",
    "DEFAULT_LEDGER_REF",
    "DEFAULT_RELEASE_STATUS",
    "DEFAULT_RELEASELEDGER_DIR_POLICY",
    "RELEASELEDGER_DIR_POLICIES",
    "ProjectConfig",
    "load_project_config",
    "project_name_or_default",
    "render_default_releaseledger_toml",
]

CONFIG_VERSION = 1
DEFAULT_LEDGER_REF = "main"
DEFAULT_LEDGER_CODE = "rl"
DEFAULT_LEDGER_NAME = "releaseledger"
DEFAULT_CHANGELOG = "CHANGELOG.md"
DEFAULT_RELEASE_STATUS = "planned"
DEFAULT_CHANGELOG_FOOTER = "<!-- generated by releaseledger -->"
DEFAULT_RELEASELEDGER_DIR_POLICY = "workspace"
RELEASELEDGER_DIR_POLICIES: frozenset[str] = frozenset({"workspace", "external"})

# Git-first defaults (design §12). Git is available but NOT required: a workspace
# outside a git worktree still works, only git-specific commands warn/fail then.
GIT_DEFAULT_BASE = "previous_release_tag"
GIT_DEFAULT_HEAD = "HEAD"
GIT_DEFAULT_INCLUDE_MERGES = "nontrivial"
GIT_DEFAULT_PREVIOUS_TAG_PATTERNS: tuple[str, ...] = ("v{version}", "{version}")
GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE = False
GIT_DEFAULT_MAX_COMMITS = 500
GIT_DEFAULT_MAX_DIFF_CHARS = 12000
GIT_DEFAULT_CANDIDATE_STATUS = "draft"
GIT_INCLUDE_MERGE_POLICIES: frozenset[str] = frozenset(
    {"never", "always", "nontrivial"}
)

# Default Jinja2-style changelog body template. Rendered once per release.
# Built via implicit string concatenation so each source line stays short;
# the rendered template content is unchanged.
DEFAULT_CHANGELOG_TEMPLATE_BODY = (
    "## {% if release.date %}"
    "[{{ release.version }}] - {{ release.date }}"
    "{% else %}[{{ release.version }}] - Unreleased"
    "{% endif %}\n"
    "\n"
    "{% for group in groups %}\n"
    "### {{ group.title }}\n"
    "{% for entry in group.entries %}\n"
    "- {% if entry.breaking %}**BREAKING:** {% endif %}"
    "{{ entry.summary }}\n"
    "{% endfor %}\n"
    "\n"
    "{% endfor %}\n"
)

# Keep a Changelog 1.1.0 body template.
# Renders [YANKED] marker for yanked releases.
DEFAULT_KEEPACHANGELOG_TEMPLATE_BODY = (
    "## [{{ release.version }}] - "
    "{% if release.date %}{{ release.date }}{% else %}Unreleased{% endif %}"
    "{% if release.yanked %} [YANKED]{% endif %}\n"
    "\n"
    "{% for group in groups %}\n"
    "### {{ group.title }}\n"
    "{% for entry in group.entries %}\n"
    "- {% if entry.breaking %}**BREAKING:** {% endif %}"
    "{{ entry.summary }}\n"
    "{% endfor %}\n"
    "\n"
    "{% endfor %}\n"
)

# Keep a Changelog 1.1.0 preamble text.
KEEPACHANGELOG_PREAMBLE = (
    "All notable changes to this project will be documented in this file.\n"
    "\n"
    "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), "
    "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
)

ALLOWED_TOP_LEVEL_KEYS = {
    "config_version",
    "releaseledger_dir",
    "ledger_ref",
    "ledger_parent_ref",
    "ledger_next_entry_number",
    "ledger_branch_guard",
    "ledger",
    "release",
    "changelog",
    "releaseledger_dir_policy",
    "git",
}
ALLOWED_LEDGER_KEYS = {"code", "name"}
ALLOWED_RELEASE_KEYS = {
    "default_changelog",
    "default_status",
    "allow_dirty_worktree",
}
ALLOWED_GIT_KEYS = {
    "enabled",
    "default_base",
    "default_head",
    "previous_tag_patterns",
    "include_merges",
    "require_clean_worktree",
    "max_commits",
    "max_diff_chars_per_commit",
    "candidate_status",
}
ALLOWED_CHANGELOG_KEYS = {
    "output",
    "header",
    "body",
    "footer",
    "trim",
    "render_always",
    "postprocessors",
    "standard",
    "group_mode",
    "link_references",
    "repository_url",
    "tag_prefix",
    "compare_url_template",
    "release_url_template",
    "preamble",
    "semver",
    "unreleased",
    "templates",
}


@dataclass(frozen=True)
class ProjectConfig:
    """Parsed and validated project configuration values."""

    config_version: int = CONFIG_VERSION
    releaseledger_dir: str = ".releaseledger"
    ledger_ref: str = DEFAULT_LEDGER_REF
    ledger_parent_ref: str = ""
    ledger_next_entry_number: int = 1
    ledger_branch_guard: str = "off"
    ledger_code: str = DEFAULT_LEDGER_CODE
    ledger_name: str = DEFAULT_LEDGER_NAME
    default_changelog: str = DEFAULT_CHANGELOG
    default_status: str = DEFAULT_RELEASE_STATUS
    allow_dirty_worktree: bool = True
    changelog_output: str = DEFAULT_CHANGELOG
    changelog_header: str = ""
    changelog_body: str = DEFAULT_CHANGELOG_TEMPLATE_BODY
    changelog_footer: str = DEFAULT_CHANGELOG_FOOTER
    changelog_trim: bool = True
    changelog_render_always: bool = False
    changelog_postprocessors: tuple[dict[str, str], ...] = ()
    releaseledger_dir_policy: str = DEFAULT_RELEASELEDGER_DIR_POLICY
    # Keep a Changelog 1.1.0 profile fields
    changelog_standard: str = ""
    changelog_group_mode: str = "extended"
    changelog_link_references: bool = False
    changelog_repository_url: str = ""
    changelog_tag_prefix: str = "v"
    changelog_compare_url_template: str = ""
    changelog_release_url_template: str = ""
    changelog_preamble: str = ""
    changelog_semver: bool = False
    changelog_unreleased: bool = True
    changelog_templates: dict[str, dict[str, Any]] | None = None
    # Git-first defaults (design §12).
    git_enabled: bool = True
    git_default_base: str = GIT_DEFAULT_BASE
    git_default_head: str = GIT_DEFAULT_HEAD
    git_previous_tag_patterns: tuple[str, ...] = GIT_DEFAULT_PREVIOUS_TAG_PATTERNS
    git_include_merges: str = GIT_DEFAULT_INCLUDE_MERGES
    git_require_clean_worktree: bool = GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE
    git_max_commits: int = GIT_DEFAULT_MAX_COMMITS
    git_max_diff_chars_per_commit: int = GIT_DEFAULT_MAX_DIFF_CHARS
    git_candidate_status: str = GIT_DEFAULT_CANDIDATE_STATUS


def _require_str(value: object, key: str, source: str) -> str:
    if not isinstance(value, str):
        raise LaunchError(
            f"Config key {key!r} in {source} must be a string.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return value


def _require_bool(value: object, key: str, source: str) -> bool:
    if not isinstance(value, bool):
        raise LaunchError(
            f"Config key {key!r} in {source} must be a boolean.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return value


def _require_int(value: object, key: str, source: str) -> int:
    # ``bool`` is a subclass of ``int``; reject it explicitly.
    if isinstance(value, bool) or not isinstance(value, int):
        raise LaunchError(
            f"Config key {key!r} in {source} must be an integer.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return value


def _require_str_list(value: object, key: str, source: str) -> tuple[str, ...]:
    """Validate a config list of non-empty strings (e.g. tag patterns)."""
    if not isinstance(value, (list, tuple)):
        raise LaunchError(
            f"Config key {key!r} in {source} must be a list.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    validated: list[str] = []
    for index, item in enumerate(value):
        if not isinstance(item, str) or not item.strip():
            raise LaunchError(
                f"Config key {key!r}[{index}] in {source} must be a non-empty string.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        validated.append(item)
    return tuple(validated)


def _require_postprocessors(value: object, source: str) -> tuple[dict[str, str], ...]:
    """Validate ``[changelog].postprocessors`` as mappings of pattern/replace."""
    if not isinstance(value, (list, tuple)):
        raise LaunchError(
            f"Config key 'changelog.postprocessors' in {source} must be a list.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    validated: list[dict[str, str]] = []
    for index, item in enumerate(value):
        if not isinstance(item, dict):
            raise LaunchError(
                f"Config key 'changelog.postprocessors[{index}]' in {source} "
                "must be a mapping.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        pattern = item.get("pattern")
        replace = item.get("replace")
        if not isinstance(pattern, str) or not isinstance(replace, str):
            raise LaunchError(
                f"Config key 'changelog.postprocessors[{index}]' in {source} "
                "must have string 'pattern' and 'replace' fields.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        validated.append({"pattern": pattern, "replace": replace})
    return tuple(validated)


def _require_templates(value: object, source: str) -> dict[str, dict[str, Any]] | None:
    """Validate ``[changelog].templates`` as a mapping of template profiles."""
    if value is None:
        return None
    if not isinstance(value, dict):
        raise LaunchError(
            f"Config key 'changelog.templates' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    validated: dict[str, dict[str, Any]] = {}
    for name, profile in value.items():
        if not isinstance(name, str):
            raise LaunchError(
                f"Template name in 'changelog.templates' in {source} must be a string.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        if not isinstance(profile, dict):
            raise LaunchError(
                f"Template profile '{name}' in {source} must be a mapping.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        validated[name] = profile
    return validated


def _config_from_dict(data: dict[str, Any], source: str) -> ProjectConfig:
    unknown = sorted(k for k in data if k not in ALLOWED_TOP_LEVEL_KEYS)
    if unknown:
        raise LaunchError(
            f"Unknown config keys in {source}: {', '.join(unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    releaseledger_dir = _require_str(
        data.get("releaseledger_dir", ".releaseledger"), "releaseledger_dir", source
    )
    if not releaseledger_dir.strip():
        raise LaunchError(
            "Config key 'releaseledger_dir' must be a non-empty string.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    ledger_section = data.get("ledger", {})
    if not isinstance(ledger_section, dict):
        raise LaunchError(
            f"Config table 'ledger' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    ledger_unknown = sorted(k for k in ledger_section if k not in ALLOWED_LEDGER_KEYS)
    if ledger_unknown:
        raise LaunchError(
            f"Unknown 'ledger' keys in {source}: {', '.join(ledger_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    release_section = data.get("release", {})
    if not isinstance(release_section, dict):
        raise LaunchError(
            f"Config table 'release' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    release_unknown = sorted(
        k for k in release_section if k not in ALLOWED_RELEASE_KEYS
    )
    if release_unknown:
        raise LaunchError(
            f"Unknown 'release' keys in {source}: {', '.join(release_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    changelog_section = data.get("changelog", {})
    if not isinstance(changelog_section, dict):
        raise LaunchError(
            f"Config table 'changelog' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    changelog_unknown = sorted(
        k for k in changelog_section if k not in ALLOWED_CHANGELOG_KEYS
    )
    if changelog_unknown:
        raise LaunchError(
            f"Unknown 'changelog' keys in {source}: {', '.join(changelog_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    git_section = data.get("git", {})
    if not isinstance(git_section, dict):
        raise LaunchError(
            f"Config table 'git' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    git_unknown = sorted(k for k in git_section if k not in ALLOWED_GIT_KEYS)
    if git_unknown:
        raise LaunchError(
            f"Unknown 'git' keys in {source}: {', '.join(git_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    git_include_merges = _require_str(
        git_section.get("include_merges", GIT_DEFAULT_INCLUDE_MERGES),
        "git.include_merges",
        source,
    )
    if git_include_merges not in GIT_INCLUDE_MERGE_POLICIES:
        raise LaunchError(
            f"Config key 'git.include_merges' in {source} must be one of"
            f" {', '.join(sorted(GIT_INCLUDE_MERGE_POLICIES))}.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    policy = _require_str(
        data.get("releaseledger_dir_policy", DEFAULT_RELEASELEDGER_DIR_POLICY),
        "releaseledger_dir_policy",
        source,
    )
    if policy not in RELEASELEDGER_DIR_POLICIES:
        raise LaunchError(
            f"Config key 'releaseledger_dir_policy' in {source}"
            " must be 'workspace' or 'external'.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    return ProjectConfig(
        config_version=_require_int(
            data.get("config_version", CONFIG_VERSION), "config_version", source
        ),
        releaseledger_dir=releaseledger_dir,
        releaseledger_dir_policy=policy,
        ledger_ref=_require_str(
            data.get("ledger_ref", DEFAULT_LEDGER_REF), "ledger_ref", source
        ),
        ledger_parent_ref=_require_str(
            data.get("ledger_parent_ref", ""), "ledger_parent_ref", source
        ),
        ledger_next_entry_number=_require_int(
            data.get("ledger_next_entry_number", 1),
            "ledger_next_entry_number",
            source,
        ),
        ledger_branch_guard=_require_str(
            data.get("ledger_branch_guard", "off"), "ledger_branch_guard", source
        ),
        ledger_code=_require_str(
            ledger_section.get("code", DEFAULT_LEDGER_CODE), "ledger.code", source
        ),
        ledger_name=_require_str(
            ledger_section.get("name", DEFAULT_LEDGER_NAME), "ledger.name", source
        ),
        default_changelog=_require_str(
            release_section.get("default_changelog", DEFAULT_CHANGELOG),
            "release.default_changelog",
            source,
        ),
        default_status=_require_str(
            release_section.get("default_status", DEFAULT_RELEASE_STATUS),
            "release.default_status",
            source,
        ),
        allow_dirty_worktree=_require_bool(
            release_section.get("allow_dirty_worktree", True),
            "release.allow_dirty_worktree",
            source,
        ),
        changelog_output=_require_str(
            changelog_section.get("output", DEFAULT_CHANGELOG),
            "changelog.output",
            source,
        ),
        changelog_header=_require_str(
            changelog_section.get("header", ""), "changelog.header", source
        ),
        changelog_body=_require_str(
            changelog_section.get("body", DEFAULT_CHANGELOG_TEMPLATE_BODY),
            "changelog.body",
            source,
        ),
        changelog_footer=_require_str(
            changelog_section.get("footer", DEFAULT_CHANGELOG_FOOTER),
            "changelog.footer",
            source,
        ),
        changelog_trim=_require_bool(
            changelog_section.get("trim", True), "changelog.trim", source
        ),
        changelog_render_always=_require_bool(
            changelog_section.get("render_always", False),
            "changelog.render_always",
            source,
        ),
        changelog_postprocessors=_require_postprocessors(
            changelog_section.get("postprocessors", []), source
        ),
        # Keep a Changelog 1.1.0 profile fields
        changelog_standard=_require_str(
            changelog_section.get("standard", ""), "changelog.standard", source
        ),
        changelog_group_mode=_require_str(
            changelog_section.get("group_mode", "extended"),
            "changelog.group_mode",
            source,
        ),
        changelog_link_references=_require_bool(
            changelog_section.get("link_references", False),
            "changelog.link_references",
            source,
        ),
        changelog_repository_url=_require_str(
            changelog_section.get("repository_url", ""),
            "changelog.repository_url",
            source,
        ),
        changelog_tag_prefix=_require_str(
            changelog_section.get("tag_prefix", "v"), "changelog.tag_prefix", source
        ),
        changelog_compare_url_template=_require_str(
            changelog_section.get("compare_url_template", ""),
            "changelog.compare_url_template",
            source,
        ),
        changelog_release_url_template=_require_str(
            changelog_section.get("release_url_template", ""),
            "changelog.release_url_template",
            source,
        ),
        changelog_preamble=_require_str(
            changelog_section.get("preamble", ""), "changelog.preamble", source
        ),
        changelog_semver=_require_bool(
            changelog_section.get("semver", False), "changelog.semver", source
        ),
        changelog_unreleased=_require_bool(
            changelog_section.get("unreleased", True), "changelog.unreleased", source
        ),
        changelog_templates=_require_templates(
            changelog_section.get("templates", None), source
        ),
        git_enabled=_require_bool(
            git_section.get("enabled", True), "git.enabled", source
        ),
        git_default_base=_require_str(
            git_section.get("default_base", GIT_DEFAULT_BASE),
            "git.default_base",
            source,
        ),
        git_default_head=_require_str(
            git_section.get("default_head", GIT_DEFAULT_HEAD),
            "git.default_head",
            source,
        ),
        git_previous_tag_patterns=_require_str_list(
            git_section.get("previous_tag_patterns", GIT_DEFAULT_PREVIOUS_TAG_PATTERNS),
            "git.previous_tag_patterns",
            source,
        ),
        git_include_merges=git_include_merges,
        git_require_clean_worktree=_require_bool(
            git_section.get(
                "require_clean_worktree", GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE
            ),
            "git.require_clean_worktree",
            source,
        ),
        git_max_commits=_require_int(
            git_section.get("max_commits", GIT_DEFAULT_MAX_COMMITS),
            "git.max_commits",
            source,
        ),
        git_max_diff_chars_per_commit=_require_int(
            git_section.get("max_diff_chars_per_commit", GIT_DEFAULT_MAX_DIFF_CHARS),
            "git.max_diff_chars_per_commit",
            source,
        ),
        git_candidate_status=_require_str(
            git_section.get("candidate_status", GIT_DEFAULT_CANDIDATE_STATUS),
            "git.candidate_status",
            source,
        ),
    )


def load_project_config(config_path: Path) -> ProjectConfig:
    """Load and validate the project TOML at ``config_path``."""
    if not config_path.is_file():
        raise LaunchError(
            f"Project config not found: {config_path}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            remediation=["Run `releaseledger init` to create the config."],
        )
    try:
        with config_path.open("rb") as handle:
            data = tomllib.load(handle)
    except tomllib.TOMLDecodeError as exc:
        raise LaunchError(
            f"Failed to parse {config_path.name}: {exc}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        ) from exc
    return _config_from_dict(data, config_path.name)


def project_name_or_default(config_path: Path, workspace_root: Path) -> str:
    """Return the configured project name, falling back to the directory name."""
    if config_path.is_file():
        try:
            config = load_project_config(config_path)
        except LaunchError:
            config = ProjectConfig()
        if config.ledger_name and config.ledger_name != DEFAULT_LEDGER_NAME:
            return config.ledger_name
    return workspace_root.name or DEFAULT_LEDGER_NAME


def render_default_releaseledger_toml(
    *,
    releaseledger_dir: str = ".releaseledger",
    project_name: str = DEFAULT_LEDGER_NAME,
    ledger_ref: str = DEFAULT_LEDGER_REF,
    policy: str = DEFAULT_RELEASELEDGER_DIR_POLICY,
) -> str:
    """Render the canonical default ``.releaseledger.toml`` content."""
    # Normalize path separators to forward slashes so the value is portable
    # across platforms and yields a valid TOML basic string. Backslashes are
    # escape characters in TOML and would corrupt Windows values such as
    # "..\ext-rl" produced by os.path.relpath.
    normalized_dir = releaseledger_dir.replace("\\", "/")
    lines = [
        "# Project-local releaseledger configuration.",
        "# This file lives in the source project root.",
        f"config_version = {CONFIG_VERSION}",
        f'releaseledger_dir = "{normalized_dir}"',
    ]
    if policy != DEFAULT_RELEASELEDGER_DIR_POLICY:
        lines.append(f'releaseledger_dir_policy = "{policy}"')
    lines.extend(
        [
            "",
            "# Branch-scoped release state. This block is safe to commit.",
            f'ledger_ref = "{ledger_ref}"',
            'ledger_parent_ref = ""',
            "ledger_next_entry_number = 1",
            'ledger_branch_guard = "off"',
            "",
            "# Cross-ledger identity. Local record IDs stay "
            "unchanged; global refs are derived.",
            "[ledger]",
            f'code = "{DEFAULT_LEDGER_CODE}"',
            f'name = "{project_name}"',
            "",
            "# Release defaults.",
            "[release]",
            f'default_changelog = "{DEFAULT_CHANGELOG}"',
            f'default_status = "{DEFAULT_RELEASE_STATUS}"',
            "allow_dirty_worktree = true",
            "# Changelog build defaults.",
            "[changelog]",
            f'output = "{DEFAULT_CHANGELOG}"',
            'standard = "keepachangelog-1.1.0"',
            'group_mode = "keepachangelog"',
            "link_references = true",
            'repository_url = ""',
            'tag_prefix = "v"',
            'compare_url_template = ""',
            'release_url_template = ""',
            'preamble = ""',
            "semver = true",
            "unreleased = true",
            "trim = true",
            "render_always = false",
            'header = ""',
            # The body template holds literal Jinja2 braces; keep it out of any
            # f-string so braces are never doubled. A newline immediately after
            # the opening triple quote is trimmed by the TOML parser on read-back.
            f'body = """\n{DEFAULT_KEEPACHANGELOG_TEMPLATE_BODY}"""',
            f'footer = "{DEFAULT_CHANGELOG_FOOTER}"',
            "postprocessors = []",
        ]
    )
    lines.extend(
        [
            "",
            "# Git-first release evidence. Git is optional: releaseledger keeps",
            "# working outside a git worktree and only git-specific commands warn.",
            "[git]",
            "enabled = true",
            f'default_base = "{GIT_DEFAULT_BASE}"',
            f'default_head = "{GIT_DEFAULT_HEAD}"',
            'previous_tag_patterns = ["v{version}", "{version}"]',
            f'include_merges = "{GIT_DEFAULT_INCLUDE_MERGES}"',
            f"require_clean_worktree ="
            f" {str(GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE).lower()}",
            f"max_commits = {GIT_DEFAULT_MAX_COMMITS}",
            f"max_diff_chars_per_commit = {GIT_DEFAULT_MAX_DIFF_CHARS}",
            f'candidate_status = "{GIT_DEFAULT_CANDIDATE_STATUS}"',
        ]
    )
    return "\n".join(lines) + "\n"


def validate_releaseledger_dir_value(value: str, *, source: str) -> str:
    """Validate a ``releaseledger_dir`` config value before writing/using it."""
    if not isinstance(value, str) or not value.strip():
        raise LaunchError(
            "releaseledger_dir must be a non-empty string.",
            code=CODE_USAGE_ERROR,
            exit_code=2,
        )
    return value
