"""Project-local TOML configuration for releaseledger (version 2).

This module owns parsing, validating, and rendering the canonical
``.ledger/releaseledger/config.toml`` file. Storage topology is not
configured here; the canonical project manifest owns that. The legacy
config version 1 fields (``releaseledger_dir``, ``releaseledger_dir_policy``,
``ledger_next_entry_number``, ``ledger.name``) are not recognised.

Path resolution relative to the config file lives in
:mod:`releaseledger.storage.paths`; this module deliberately has no
filesystem discovery so it can be unit-tested against plain dicts and
strings.
"""

from __future__ import annotations

import dataclasses
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import ledgercore
import tomlkit
import tomlkit.items

from releaseledger.errors import CODE_CONFIG_ERROR, LaunchError

__all__ = [
    "ALLOWED_CHANGELOG_KEYS",
    "ALLOWED_GIT_KEYS",
    "ALLOWED_LEDGER_KEYS",
    "ALLOWED_RELEASE_KEYS",
    "ALLOWED_TOP_LEVEL_KEYS",
    "CONFIG_VERSION",
    "DEFAULT_CHANGELOG",
    "DEFAULT_CHANGELOG_FOOTER",
    "DEFAULT_CHANGELOG_TEMPLATE_BODY",
    "DEFAULT_KEEPACHANGELOG_TEMPLATE_BODY",
    "DEFAULT_LEDGER_CODE",
    "DEFAULT_LEDGER_NAME",
    "DEFAULT_LEDGER_REF",
    "GIT_DEFAULT_BASE",
    "GIT_DEFAULT_CANDIDATE_STATUS",
    "GIT_DEFAULT_HEAD",
    "GIT_DEFAULT_INCLUDE_MERGES",
    "GIT_DEFAULT_MAX_COMMITS",
    "GIT_DEFAULT_MAX_DIFF_CHARS",
    "GIT_DEFAULT_PREVIOUS_TAG_PATTERNS",
    "GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE",
    "GIT_INCLUDE_MERGE_POLICIES",
    "KEEPACHANGELOG_PREAMBLE",
    "ProjectConfig",
    "REMOVED_FIELDS",
    "load_project_config",
    "render_default_project_config",
    "update_project_config",
    "render_default_releaseledger_toml",
    "write_project_config",
]

CONFIG_VERSION = 2

DEFAULT_LEDGER_REF = "main"
DEFAULT_LEDGER_CODE = "rl"
DEFAULT_LEDGER_NAME = "releaseledger"
DEFAULT_CHANGELOG = "CHANGELOG.md"
DEFAULT_RELEASE_STATUS = "planned"
DEFAULT_CHANGELOG_FOOTER = "<!-- generated by releaseledger -->"

# Fields that the v1 config understood and that v2 no longer accepts.
# Listed here so the parser and the default renderer can both reject them
# with a single source of truth.
REMOVED_FIELDS: frozenset[str] = frozenset(
    {
        "releaseledger_dir",
        "releaseledger_dir_policy",
        "ledger_next_entry_number",
        # ledger.name is migrated out, but lives under [ledger]; rejected
        # explicitly by ``ALLOWED_LEDGER_KEYS``.
    }
)

# Git-first defaults (design §12). Git is available but NOT required: a
# workspace outside a git worktree still works; only git-specific commands
# warn/fail then.
GIT_DEFAULT_BASE = "previous_release_tag"
GIT_DEFAULT_HEAD = "HEAD"
GIT_DEFAULT_INCLUDE_MERGES = "nontrivial"
GIT_DEFAULT_PREVIOUS_TAG_PATTERNS: tuple[str, ...] = ("v{version}", "{version}")
GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE = False
GIT_DEFAULT_MAX_COMMITS = 500
GIT_DEFAULT_MAX_DIFF_CHARS = 12000
GIT_DEFAULT_CANDIDATE_STATUS = "draft"
GIT_INCLUDE_MERGE_POLICIES: frozenset[str] = frozenset(
    {"never", "always", "nontrivial"}
)

# Default Jinja2-style changelog body template. Rendered once per release.
DEFAULT_CHANGELOG_TEMPLATE_BODY = (
    "## {% if release.date %}"
    "[{{ release.version }}] - {{ release.date }}"
    "{% else %}[{{ release.version }}] - Unreleased"
    "{% endif %}\n"
    "\n"
    "{% for group in groups %}\n"
    "### {{ group.title }}\n"
    "{% for entry in group.entries %}\n"
    "- {% if entry.breaking %}**BREAKING:** {% endif %}"
    "{{ entry.summary }}\n"
    "{% endfor %}\n"
    "\n"
    "{% endfor %}\n"
)

# Keep a Changelog 1.1.0 body template.
DEFAULT_KEEPACHANGELOG_TEMPLATE_BODY = (
    "## [{{ release.version }}] - "
    "{% if release.date %}{{ release.date }}{% else %}Unreleased{% endif %}"
    "{% if release.yanked %} [YANKED]{% endif %}\n"
    "\n"
    "{% for group in groups %}\n"
    "### {{ group.title }}\n"
    "{% for entry in group.entries %}\n"
    "- {% if entry.breaking %}**BREAKING:** {% endif %}"
    "{{ entry.summary }}\n"
    "{% endfor %}\n"
    "\n"
    "{% endfor %}\n"
)

# Keep a Changelog 1.1.0 preamble text.
KEEPACHANGELOG_PREAMBLE = (
    "All notable changes to this project will be documented in this file.\n"
    "\n"
    "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), "
    "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
)

ALLOWED_TOP_LEVEL_KEYS: frozenset[str] = frozenset(
    {
        "config_version",
        "ledger_ref",
        "ledger_parent_ref",
        "ledger_branch_guard",
        "ledger",
        "release",
        "changelog",
        "git",
    }
)
ALLOWED_LEDGER_KEYS: frozenset[str] = frozenset({"code"})
ALLOWED_RELEASE_KEYS: frozenset[str] = frozenset(
    {
        "default_changelog",
        "default_status",
        "allow_dirty_worktree",
    }
)
ALLOWED_CHANGELOG_KEYS: frozenset[str] = frozenset(
    {
        "output",
        "header",
        "body",
        "footer",
        "trim",
        "render_always",
        "postprocessors",
        "standard",
        "group_mode",
        "link_references",
        "repository_url",
        "tag_prefix",
        "compare_url_template",
        "release_url_template",
        "preamble",
        "semver",
        "unreleased",
        "templates",
    }
)
ALLOWED_GIT_KEYS: frozenset[str] = frozenset(
    {
        "enabled",
        "default_base",
        "default_head",
        "previous_tag_patterns",
        "include_merges",
        "require_clean_worktree",
        "max_commits",
        "max_diff_chars_per_commit",
        "candidate_status",
    }
)


@dataclass(frozen=True, slots=True)
class ProjectConfig:
    """Parsed and validated project configuration values (version 2).

    The dataclass carries no storage topology. Project identity and
    storage live in the Ledgercore-managed ``.ledger/ledger.toml``.
    """

    config_version: int = CONFIG_VERSION
    ledger_ref: str = DEFAULT_LEDGER_REF
    ledger_parent_ref: str = ""
    ledger_branch_guard: str = "off"
    ledger_code: str = DEFAULT_LEDGER_CODE
    default_changelog: str = DEFAULT_CHANGELOG
    default_status: str = DEFAULT_RELEASE_STATUS
    allow_dirty_worktree: bool = True
    changelog_output: str = DEFAULT_CHANGELOG
    changelog_header: str = ""
    changelog_body: str = DEFAULT_CHANGELOG_TEMPLATE_BODY
    changelog_footer: str = DEFAULT_CHANGELOG_FOOTER
    changelog_trim: bool = True
    changelog_render_always: bool = False
    changelog_postprocessors: tuple[dict[str, str], ...] = ()
    changelog_standard: str = ""
    changelog_group_mode: str = "extended"
    changelog_link_references: bool = False
    changelog_repository_url: str = ""
    changelog_tag_prefix: str = "v"
    changelog_compare_url_template: str = ""
    changelog_release_url_template: str = ""
    changelog_preamble: str = ""
    changelog_semver: bool = False
    changelog_unreleased: bool = True
    changelog_templates: dict[str, dict[str, Any]] | None = None
    git_enabled: bool = True
    git_default_base: str = GIT_DEFAULT_BASE
    git_default_head: str = GIT_DEFAULT_HEAD
    git_previous_tag_patterns: tuple[str, ...] = GIT_DEFAULT_PREVIOUS_TAG_PATTERNS
    git_include_merges: str = GIT_DEFAULT_INCLUDE_MERGES
    git_require_clean_worktree: bool = GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE
    git_max_commits: int = GIT_DEFAULT_MAX_COMMITS
    git_max_diff_chars_per_commit: int = GIT_DEFAULT_MAX_DIFF_CHARS
    git_candidate_status: str = GIT_DEFAULT_CANDIDATE_STATUS

    def replace(self, **changes: Any) -> ProjectConfig:
        """Typed shallow copy. Mirrors :func:`dataclasses.replace`."""

        return dataclasses.replace(self, **changes)


def _require_str(value: object, key: str, source: str) -> str:
    if not isinstance(value, str):
        raise LaunchError(
            f"Config key {key!r} in {source} must be a string.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return value


def _require_bool(value: object, key: str, source: str) -> bool:
    if not isinstance(value, bool):
        raise LaunchError(
            f"Config key {key!r} in {source} must be a boolean.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return value


def _require_int(value: object, key: str, source: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise LaunchError(
            f"Config key {key!r} in {source} must be an integer.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return value


def _require_str_list(value: object, key: str, source: str) -> tuple[str, ...]:
    if not isinstance(value, (list, tuple)):
        raise LaunchError(
            f"Config key {key!r} in {source} must be a list.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    validated: list[str] = []
    for index, item in enumerate(value):
        if not isinstance(item, str) or not item.strip():
            raise LaunchError(
                f"Config key {key!r}[{index}] in {source} must be a non-empty string.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        validated.append(item)
    return tuple(validated)


def _require_postprocessors(value: object, source: str) -> tuple[dict[str, str], ...]:
    if not isinstance(value, (list, tuple)):
        raise LaunchError(
            f"Config key 'changelog.postprocessors' in {source} must be a list.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    validated: list[dict[str, str]] = []
    for index, item in enumerate(value):
        if not isinstance(item, dict):
            raise LaunchError(
                f"Config key 'changelog.postprocessors[{index}]' in {source} "
                "must be a mapping.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        pattern = item.get("pattern")
        replace = item.get("replace")
        if not isinstance(pattern, str) or not isinstance(replace, str):
            raise LaunchError(
                f"Config key 'changelog.postprocessors[{index}]' in {source} "
                "must have string 'pattern' and 'replace' fields.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        validated.append({"pattern": pattern, "replace": replace})
    return tuple(validated)


def _require_templates(value: object, source: str) -> dict[str, dict[str, Any]] | None:
    if value is None:
        return None
    if not isinstance(value, dict):
        raise LaunchError(
            f"Config key 'changelog.templates' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    validated: dict[str, dict[str, Any]] = {}
    for name, profile in value.items():
        if not isinstance(name, str):
            raise LaunchError(
                f"Template name in 'changelog.templates' in {source} must be a string.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        if not isinstance(profile, dict):
            raise LaunchError(
                f"Template profile '{name}' in {source} must be a mapping.",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
            )
        validated[name] = profile
    return validated


def _reject_removed_fields(data: Mapping[str, Any], source: str) -> None:
    """Reject v1-only top-level fields and ``ledger.name`` with a clear error."""

    removed = sorted(set(data) & REMOVED_FIELDS)
    if removed:
        raise LaunchError(
            f"Removed config keys in {source}: {', '.join(removed)}. "
            "Config version 2 no longer accepts these fields; migrate with "
            "`releaseledger storage migrate plan`.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"source": source, "removed_keys": removed},
        )
    ledger_section = data.get("ledger")
    if isinstance(ledger_section, Mapping) and "name" in ledger_section:
        raise LaunchError(
            f"Removed config key 'ledger.name' in {source}. The project "
            "name now lives in the canonical Ledger manifest.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"source": source, "removed_keys": ["ledger.name"]},
        )


def _config_from_dict(data: Mapping[str, Any], source: str) -> ProjectConfig:
    if not isinstance(data, Mapping):
        raise LaunchError(
            f"Config file {source} must contain a TOML table at the top level.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    _reject_removed_fields(data, source)

    unknown = sorted(set(data) - ALLOWED_TOP_LEVEL_KEYS)
    if unknown:
        raise LaunchError(
            f"Unknown config keys in {source}: {', '.join(unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    config_version = _require_int(
        data.get("config_version", CONFIG_VERSION), "config_version", source
    )
    if config_version != CONFIG_VERSION:
        raise LaunchError(
            f"Config version {config_version} in {source} is not supported; "
            f"this releaseledger build requires config_version = {CONFIG_VERSION}.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"source": source, "found": config_version, "required": CONFIG_VERSION},
        )

    ledger_section = data.get("ledger", {})
    if not isinstance(ledger_section, Mapping):
        raise LaunchError(
            f"Config table 'ledger' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    ledger_unknown = sorted(set(ledger_section) - ALLOWED_LEDGER_KEYS)
    if ledger_unknown:
        raise LaunchError(
            f"Unknown 'ledger' keys in {source}: {', '.join(ledger_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    release_section = data.get("release", {})
    if not isinstance(release_section, Mapping):
        raise LaunchError(
            f"Config table 'release' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    release_unknown = sorted(set(release_section) - ALLOWED_RELEASE_KEYS)
    if release_unknown:
        raise LaunchError(
            f"Unknown 'release' keys in {source}: {', '.join(release_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    changelog_section = data.get("changelog", {})
    if not isinstance(changelog_section, Mapping):
        raise LaunchError(
            f"Config table 'changelog' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    changelog_unknown = sorted(set(changelog_section) - ALLOWED_CHANGELOG_KEYS)
    if changelog_unknown:
        raise LaunchError(
            f"Unknown 'changelog' keys in {source}: {', '.join(changelog_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    git_section = data.get("git", {})
    if not isinstance(git_section, Mapping):
        raise LaunchError(
            f"Config table 'git' in {source} must be a mapping.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    git_unknown = sorted(set(git_section) - ALLOWED_GIT_KEYS)
    if git_unknown:
        raise LaunchError(
            f"Unknown 'git' keys in {source}: {', '.join(git_unknown)}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    git_include_merges = _require_str(
        git_section.get("include_merges", GIT_DEFAULT_INCLUDE_MERGES),
        "git.include_merges",
        source,
    )
    if git_include_merges not in GIT_INCLUDE_MERGE_POLICIES:
        raise LaunchError(
            f"Config key 'git.include_merges' in {source} must be one of"
            f" {', '.join(sorted(GIT_INCLUDE_MERGE_POLICIES))}.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )

    return ProjectConfig(
        config_version=config_version,
        ledger_ref=_require_str(
            data.get("ledger_ref", DEFAULT_LEDGER_REF), "ledger_ref", source
        ),
        ledger_parent_ref=_require_str(
            data.get("ledger_parent_ref", ""), "ledger_parent_ref", source
        ),
        ledger_branch_guard=_require_str(
            data.get("ledger_branch_guard", "off"), "ledger_branch_guard", source
        ),
        ledger_code=_require_str(
            ledger_section.get("code", DEFAULT_LEDGER_CODE), "ledger.code", source
        ),
        default_changelog=_require_str(
            release_section.get("default_changelog", DEFAULT_CHANGELOG),
            "release.default_changelog",
            source,
        ),
        default_status=_require_str(
            release_section.get("default_status", DEFAULT_RELEASE_STATUS),
            "release.default_status",
            source,
        ),
        allow_dirty_worktree=_require_bool(
            release_section.get("allow_dirty_worktree", True),
            "release.allow_dirty_worktree",
            source,
        ),
        changelog_output=_require_str(
            changelog_section.get("output", DEFAULT_CHANGELOG),
            "changelog.output",
            source,
        ),
        changelog_header=_require_str(
            changelog_section.get("header", ""), "changelog.header", source
        ),
        changelog_body=_require_str(
            changelog_section.get("body", DEFAULT_CHANGELOG_TEMPLATE_BODY),
            "changelog.body",
            source,
        ),
        changelog_footer=_require_str(
            changelog_section.get("footer", DEFAULT_CHANGELOG_FOOTER),
            "changelog.footer",
            source,
        ),
        changelog_trim=_require_bool(
            changelog_section.get("trim", True), "changelog.trim", source
        ),
        changelog_render_always=_require_bool(
            changelog_section.get("render_always", False),
            "changelog.render_always",
            source,
        ),
        changelog_postprocessors=_require_postprocessors(
            changelog_section.get("postprocessors", []), source
        ),
        changelog_standard=_require_str(
            changelog_section.get("standard", ""), "changelog.standard", source
        ),
        changelog_group_mode=_require_str(
            changelog_section.get("group_mode", "extended"),
            "changelog.group_mode",
            source,
        ),
        changelog_link_references=_require_bool(
            changelog_section.get("link_references", False),
            "changelog.link_references",
            source,
        ),
        changelog_repository_url=_require_str(
            changelog_section.get("repository_url", ""),
            "changelog.repository_url",
            source,
        ),
        changelog_tag_prefix=_require_str(
            changelog_section.get("tag_prefix", "v"), "changelog.tag_prefix", source
        ),
        changelog_compare_url_template=_require_str(
            changelog_section.get("compare_url_template", ""),
            "changelog.compare_url_template",
            source,
        ),
        changelog_release_url_template=_require_str(
            changelog_section.get("release_url_template", ""),
            "changelog.release_url_template",
            source,
        ),
        changelog_preamble=_require_str(
            changelog_section.get("preamble", ""), "changelog.preamble", source
        ),
        changelog_semver=_require_bool(
            changelog_section.get("semver", False), "changelog.semver", source
        ),
        changelog_unreleased=_require_bool(
            changelog_section.get("unreleased", True),
            "changelog.unreleased",
            source,
        ),
        changelog_templates=_require_templates(
            changelog_section.get("templates", None), source
        ),
        git_enabled=_require_bool(
            git_section.get("enabled", True), "git.enabled", source
        ),
        git_default_base=_require_str(
            git_section.get("default_base", GIT_DEFAULT_BASE),
            "git.default_base",
            source,
        ),
        git_default_head=_require_str(
            git_section.get("default_head", GIT_DEFAULT_HEAD),
            "git.default_head",
            source,
        ),
        git_previous_tag_patterns=_require_str_list(
            git_section.get("previous_tag_patterns", GIT_DEFAULT_PREVIOUS_TAG_PATTERNS),
            "git.previous_tag_patterns",
            source,
        ),
        git_include_merges=git_include_merges,
        git_require_clean_worktree=_require_bool(
            git_section.get("require_clean_worktree", GIT_DEFAULT_REQUIRE_CLEAN_WORKTREE),
            "git.require_clean_worktree",
            source,
        ),
        git_max_commits=_require_int(
            git_section.get("max_commits", GIT_DEFAULT_MAX_COMMITS),
            "git.max_commits",
            source,
        ),
        git_max_diff_chars_per_commit=_require_int(
            git_section.get("max_diff_chars_per_commit", GIT_DEFAULT_MAX_DIFF_CHARS),
            "git.max_diff_chars_per_commit",
            source,
        ),
        git_candidate_status=_require_str(
            git_section.get("candidate_status", GIT_DEFAULT_CANDIDATE_STATUS),
            "git.candidate_status",
            source,
        ),
    )

def project_name_or_default(project) -> str:
    """Return the project name, falling back to the tool or directory name.

    ``project`` is a :class:`ReleaseledgerProject` or any object with
    ``layout.project_name`` and ``project_root``. The project name now
    comes from the canonical Ledger manifest; the function still
    returns a sensible string when it is missing so the CLI can render
    a human label.
    """

    layout = getattr(project, "layout", None)
    if layout is not None:
        manifest_name = getattr(layout, "project_name", None)
        if isinstance(manifest_name, str) and manifest_name.strip():
            return manifest_name
    root = getattr(project, "project_root", None)
    if root is not None:
        return Path(str(root)).name or DEFAULT_LEDGER_NAME
    return DEFAULT_LEDGER_NAME


def load_project_config(config_path: Path) -> ProjectConfig:
    """Load and validate the project TOML at ``config_path`` (version 2)."""

    if not config_path.is_file():
        raise LaunchError(
            f"Project config not found: {config_path}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"path": str(config_path)},
            remediation=[
                "Run `releaseledger init` to create the config.",
            ],
        )
    try:
        text = config_path.read_text(encoding="utf-8")
        document = tomlkit.parse(text)
    except tomlkit.exceptions.TomlKitError as exc:
        raise LaunchError(
            f"Failed to parse {config_path.name}: {exc}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"path": str(config_path)},
        ) from exc
    return _config_from_dict(document, config_path.name)


# ---------------------------------------------------------------------------
# Writer / patcher
# ---------------------------------------------------------------------------


def _stringify_changelog_body(body: str) -> str:
    """Return the body string in a TOML-safe multiline representation."""

    return body


def _config_to_tomlkit(config: ProjectConfig) -> tomlkit.TOMLDocument:
    """Render a :class:`ProjectConfig` to a fresh :mod:`tomlkit` document.

    Comments are intentionally omitted because the rendered output is the
    canonical default; the writer is paired with the patcher for round-trip
    updates, and :func:`write_project_config` keeps existing comments when
    the file is already on disk.
    """

    doc = tomlkit.document()
    doc.add("config_version", config.config_version)
    doc.add(tomlkit.comment("Branch-scoped release state. This block is safe to commit."))
    doc.add("ledger_ref", config.ledger_ref)
    doc.add("ledger_parent_ref", config.ledger_parent_ref)
    doc.add("ledger_branch_guard", config.ledger_branch_guard)
    doc.add(tomlkit.comment("Cross-ledger identity. Local record IDs stay unchanged."))
    ledger = tomlkit.table()
    ledger.add("code", config.ledger_code)
    doc.add("ledger", ledger)
    doc.add(tomlkit.comment("Release defaults."))
    release = tomlkit.table()
    release.add("default_changelog", config.default_changelog)
    release.add("default_status", config.default_status)
    release.add("allow_dirty_worktree", config.allow_dirty_worktree)
    doc.add("release", release)
    doc.add(tomlkit.comment("Changelog build defaults."))
    changelog = tomlkit.table()
    changelog.add("output", config.changelog_output)
    changelog.add("header", config.changelog_header)
    body = tomlkit.string(config.changelog_body, multiline=True)
    changelog.add("body", body)
    changelog.add("footer", config.changelog_footer)
    changelog.add("trim", config.changelog_trim)
    changelog.add("render_always", config.changelog_render_always)
    changelog.add("postprocessors", list(config.changelog_postprocessors))
    changelog.add("standard", config.changelog_standard)
    changelog.add("group_mode", config.changelog_group_mode)
    changelog.add("link_references", config.changelog_link_references)
    changelog.add("repository_url", config.changelog_repository_url)
    changelog.add("tag_prefix", config.changelog_tag_prefix)
    changelog.add("compare_url_template", config.changelog_compare_url_template)
    changelog.add("release_url_template", config.changelog_release_url_template)
    changelog.add("preamble", config.changelog_preamble)
    changelog.add("semver", config.changelog_semver)
    changelog.add("unreleased", config.changelog_unreleased)
    if config.changelog_templates is not None:
        changelog.add("templates", config.changelog_templates)
    doc.add("changelog", changelog)
    doc.add(tomlkit.comment("Git-first release evidence."))
    git = tomlkit.table()
    git.add("enabled", config.git_enabled)
    git.add("default_base", config.git_default_base)
    git.add("default_head", config.git_default_head)
    git.add("previous_tag_patterns", list(config.git_previous_tag_patterns))
    git.add("include_merges", config.git_include_merges)
    git.add("require_clean_worktree", config.git_require_clean_worktree)
    git.add("max_commits", config.git_max_commits)
    git.add("max_diff_chars_per_commit", config.git_max_diff_chars_per_commit)
    git.add("candidate_status", config.git_candidate_status)
    doc.add("git", git)
    return doc


def write_project_config(
    config_path: Path,
    config: ProjectConfig,
    *,
    preserve_comments: bool = True,
) -> None:
    """Atomically write ``config`` to ``config_path``.

    When ``preserve_comments`` is true and ``config_path`` already exists,
    the existing TOML document is read with :mod:`tomlkit`, the canonical
    v2 fields are updated in place, and removed v1 fields are stripped
    so the file conforms to the new schema. The original file is left
    unchanged on parse/validation/write failure because the write goes
    through :func:`ledgercore.atomic_write_text`.
    """

    if config.config_version != CONFIG_VERSION:
        raise LaunchError(
            "Refusing to write a config whose config_version is not 2.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"config_version": config.config_version, "required": CONFIG_VERSION},
        )

    if preserve_comments and config_path.is_file():
        try:
            text = config_path.read_text(encoding="utf-8")
            document = tomlkit.parse(text)
        except tomlkit.exceptions.TomlKitError as exc:
            raise LaunchError(
                f"Failed to parse {config_path.name}: {exc}",
                code=CODE_CONFIG_ERROR,
                exit_code=2,
                data={"path": str(config_path)},
            ) from exc
        _apply_config_to_document(document, config)
    else:
        document = _config_to_tomlkit(config)

    rendered = tomlkit.dumps(document)
    ledgercore.atomic_write_text(config_path, rendered)


def _apply_config_to_document(
    document: tomlkit.TOMLDocument, config: ProjectConfig
) -> None:
    """Mutate ``document`` so it matches ``config`` while preserving comments.

    Unknown v1 keys (``releaseledger_dir``, ``releaseledger_dir_policy``,
    ``ledger_next_entry_number``, ``ledger.name``) are removed. New
    sections are created when missing. Existing keys keep their
    surrounding comments and order where the new schema allows it.
    """

    def _set(table: Any, key: str, value: Any) -> None:
        if key in table:
            table[key] = value
        else:
            table.add(key, value)

    _set(document, "config_version", config.config_version)
    _set(document, "ledger_ref", config.ledger_ref)
    _set(document, "ledger_parent_ref", config.ledger_parent_ref)
    _set(document, "ledger_branch_guard", config.ledger_branch_guard)
    for removed in REMOVED_FIELDS:
        if removed in document:
            del document[removed]
    ledger = document.get("ledger")
    if ledger is None:
        ledger = tomlkit.table()
        document.add("ledger", ledger)
    _set(ledger, "code", config.ledger_code)
    if "name" in ledger:
        del ledger["name"]
    release = document.get("release")
    if release is None:
        release = tomlkit.table()
        document.add("release", release)
    _set(release, "default_changelog", config.default_changelog)
    _set(release, "default_status", config.default_status)
    _set(release, "allow_dirty_worktree", config.allow_dirty_worktree)
    changelog = document.get("changelog")
    if changelog is None:
        changelog = tomlkit.table()
        document.add("changelog", changelog)
    _set(changelog, "output", config.changelog_output)
    _set(changelog, "header", config.changelog_header)
    _set(changelog, "body", tomlkit.string(config.changelog_body, multiline=True))
    _set(changelog, "footer", config.changelog_footer)
    _set(changelog, "trim", config.changelog_trim)
    _set(changelog, "render_always", config.changelog_render_always)
    _set(changelog, "postprocessors", list(config.changelog_postprocessors))
    _set(changelog, "standard", config.changelog_standard)
    _set(changelog, "group_mode", config.changelog_group_mode)
    _set(changelog, "link_references", config.changelog_link_references)
    _set(changelog, "repository_url", config.changelog_repository_url)
    _set(changelog, "tag_prefix", config.changelog_tag_prefix)
    _set(changelog, "compare_url_template", config.changelog_compare_url_template)
    _set(changelog, "release_url_template", config.changelog_release_url_template)
    _set(changelog, "preamble", config.changelog_preamble)
    _set(changelog, "semver", config.changelog_semver)
    _set(changelog, "unreleased", config.changelog_unreleased)
    if config.changelog_templates is not None:
        _set(changelog, "templates", config.changelog_templates)
    elif "templates" in changelog:
        del changelog["templates"]
    git = document.get("git")
    if git is None:
        git = tomlkit.table()
        document.add("git", git)
    _set(git, "enabled", config.git_enabled)
    _set(git, "default_base", config.git_default_base)
    _set(git, "default_head", config.git_default_head)
    _set(git, "previous_tag_patterns", list(config.git_previous_tag_patterns))
    _set(git, "include_merges", config.git_include_merges)
    _set(git, "require_clean_worktree", config.git_require_clean_worktree)
    _set(git, "max_commits", config.git_max_commits)
    _set(git, "max_diff_chars_per_commit", config.git_max_diff_chars_per_commit)
    _set(git, "candidate_status", config.git_candidate_status)


def update_project_config(
    config_path: Path,
    changes: Mapping[str, Any],
) -> ProjectConfig:
    """Read, apply ``changes``, validate, and atomically write the config.

    Returns the resulting :class:`ProjectConfig`. ``changes`` keys may
    be dotted (``"ledger_ref"``, ``"changelog.body"``, ``"git.max_commits"``)
    or a mapping for nested sections. Unknown keys raise a structured
    error. The original file is unchanged on parse/validation/write
    failure because the write goes through
    :func:`ledgercore.atomic_write_text`.
    """

    if not config_path.is_file():
        raise LaunchError(
            f"Project config not found: {config_path}",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
            data={"path": str(config_path)},
            remediation=[
                "Run `releaseledger init` to create the config.",
            ],
        )
    config = load_project_config(config_path)
    updated = _apply_changes(config, changes)
    write_project_config(config_path, updated)
    return updated


def _apply_changes(
    config: ProjectConfig, changes: Mapping[str, Any]
) -> ProjectConfig:
    """Translate a dotted-key patch into a typed config update."""

    flat: dict[str, Any] = {}
    for key, value in changes.items():
        if isinstance(value, Mapping) and key in {"ledger", "release", "changelog", "git"}:
            for sub_key, sub_value in value.items():
                flat[f"{key}.{sub_key}"] = sub_value
        else:
            flat[key] = value

    if "ledger_ref" in flat:
        config = config.replace(ledger_ref=_require_str(flat["ledger_ref"], "ledger_ref", "patch"))
    if "ledger_parent_ref" in flat:
        config = config.replace(
            ledger_parent_ref=_require_str(flat["ledger_parent_ref"], "ledger_parent_ref", "patch")
        )
    if "ledger_branch_guard" in flat:
        config = config.replace(
            ledger_branch_guard=_require_str(flat["ledger_branch_guard"], "ledger_branch_guard", "patch")
        )
    if "ledger.code" in flat:
        config = config.replace(ledger_code=_require_str(flat["ledger.code"], "ledger.code", "patch"))
    if "release.default_changelog" in flat:
        config = config.replace(
            default_changelog=_require_str(
                flat["release.default_changelog"], "release.default_changelog", "patch"
            )
        )
    if "release.default_status" in flat:
        config = config.replace(
            default_status=_require_str(
                flat["release.default_status"], "release.default_status", "patch"
            )
        )
    if "release.allow_dirty_worktree" in flat:
        config = config.replace(
            allow_dirty_worktree=_require_bool(
                flat["release.allow_dirty_worktree"], "release.allow_dirty_worktree", "patch"
            )
        )
    if "changelog.body" in flat:
        config = config.replace(
            changelog_body=_require_str(flat["changelog.body"], "changelog.body", "patch")
        )
    if "changelog.footer" in flat:
        config = config.replace(
            changelog_footer=_require_str(flat["changelog.footer"], "changelog.footer", "patch")
        )
    if "git.max_commits" in flat:
        config = config.replace(
            git_max_commits=_require_int(flat["git.max_commits"], "git.max_commits", "patch")
        )
    return config


def render_default_project_config(
    *,
    ledger_ref: str = DEFAULT_LEDGER_REF,
    ledger_code: str = DEFAULT_LEDGER_CODE,
) -> str:
    """Render the canonical config v2 default text."""
    """Render the canonical config v2 default text."""

    return tomlkit.dumps(_config_to_tomlkit(ProjectConfig(ledger_ref=ledger_ref, ledger_code=ledger_code)))


def render_default_releaseledger_toml(
    *,
    releaseledger_dir: str | None = None,
    project_name: str | None = None,
    ledger_ref: str = DEFAULT_LEDGER_REF,
    policy: str | None = None,
) -> str:
    """Deprecated alias kept for one release.

    The legacy ``releaseledger_dir``/``policy`` arguments are accepted
    only to produce a structured error. The project name argument is
    ignored: the project name now lives in the canonical Ledger manifest.
    """

    if releaseledger_dir is not None or policy is not None:
        raise LaunchError(
            "releaseledger_dir/releaseledger_dir_policy are no longer "
            "supported; the canonical Ledger project owns the data mount.",
            code=CODE_CONFIG_ERROR,
            exit_code=2,
        )
    return render_default_project_config(ledger_ref=ledger_ref)
