"""Tests for the conventional full-changelog-rebuild command.

Covers ``releaseledger build`` (no VERSION) and ``releaseledger build --all`` as
the whole-target-file rebuild path, while keeping the existing single-section
``releaseledger build VERSION`` behavior intact.
"""

from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from releaseledger.cli import app

runner = CliRunner()


def _json(result) -> dict[str, object]:
    assert result.exit_code == 0, result.stdout
    return json.loads(result.stdout)


def _init_project(tmp_path: Path) -> None:
    result = runner.invoke(app, ["--cwd", str(tmp_path), "init"])
    assert result.exit_code == 0, result.stdout


def _run(tmp_path: Path, *cmd: str):
    return runner.invoke(app, ["--cwd", str(tmp_path), *cmd])


def _jrun(tmp_path: Path, *cmd: str):
    return runner.invoke(app, ["--cwd", str(tmp_path), "--json", *cmd])


def _human_error(result) -> str:
    try:
        stderr = result.stderr or ""
    except ValueError:
        stderr = ""
    stdout = result.stdout or getattr(result, "output", "") or ""
    return stderr + stdout


def _seed_release(
    tmp_path: Path,
    version: str,
    *,
    released_at: str,
    summary: str,
    kind: str = "added",
    internal: bool = False,
    previous: str | None = None,
    paths: list[str] | None = None,
) -> None:
    cmd: list[str] = [
        "release",
        "tag",
        version,
        "--released-at",
        released_at,
    ]
    if previous is not None:
        cmd.extend(["--previous", previous])
    result = _run(tmp_path, *cmd)
    assert result.exit_code == 0, _human_error(result)
    add_cmd: list[str] = [
        "entry",
        "add",
        version,
        "--kind",
        kind,
        "--summary",
        summary,
    ]
    if internal:
        add_cmd.append("--internal")
    for p in paths or []:
        add_cmd.extend(["--path", p])
    result = _run(tmp_path, *add_cmd)
    assert result.exit_code == 0, _human_error(result)


def _write_keepachangelog_config(tmp_path: Path, *, repository_url: str = "") -> None:
    """Write a Keep a Changelog config with optional repository URL."""
    lines = [
        "config_version = 1",
        'releaseledger_dir = ".releaseledger"',
        'ledger_ref = "main"',
        'ledger_parent_ref = ""',
        "ledger_next_entry_number = 1",
        'ledger_branch_guard = "off"',
        "[ledger]",
        'code = "rl"',
        'name = "releaseledger"',
        "[release]",
        'default_changelog = "CHANGELOG.md"',
        'default_status = "planned"',
        "allow_dirty_worktree = true",
        "[changelog]",
        'output = "CHANGELOG.md"',
        'standard = "keepachangelog-1.1.0"',
        'group_mode = "keepachangelog"',
        "link_references = true",
        f'repository_url = "{repository_url}"',
        'tag_prefix = "v"',
        'compare_url_template = ""',
        'release_url_template = ""',
        'preamble = ""',
        "semver = true",
        "unreleased = true",
        "trim = true",
        "render_always = false",
        'header = ""',
        'footer = "<!-- generated by releaseledger -->"',
        "postprocessors = []",
    ]
    (tmp_path / ".releaseledger.toml").write_text("\n".join(lines) + "\n")


class TestFullBuild:
    @staticmethod
    def _seed_two_releases(tmp_path: Path) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(tmp_path)
        _seed_release(
            tmp_path,
            "0.1.0",
            released_at="2026-01-10",
            summary="Add first public feature",
            kind="added",
        )
        _seed_release(
            tmp_path,
            "0.2.0",
            released_at="2026-02-20",
            summary="Add second public feature",
            kind="added",
            previous="0.1.0",
        )

    def test_build_no_version_rebuilds_all(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        result = _run(tmp_path, "build")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        assert "## [0.2.0] - 2026-02-20" in text
        assert "## [0.1.0] - 2026-01-10" in text
        assert "- Add first public feature" in text
        assert "- Add second public feature" in text

    def test_build_all_equivalent_to_no_version(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        result_no_version = _jrun(tmp_path, "build")
        result_all = _jrun(tmp_path, "build", "--all")
        payload_no = _json(result_no_version)
        payload_all = _json(result_all)
        assert payload_no["result"]["versions"] == payload_all["result"]["versions"]
        assert payload_no["result"]["document"] == payload_all["result"]["document"]

    def test_build_version_remains_single_section(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        result = _run(tmp_path, "build", "0.2.0", "--target-file", "CHANGELOG.md")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        # Single-section build inserts exactly one section.
        assert "## [0.2.0] - 2026-02-20" in text
        assert "## [0.1.0]" not in text
        # Refuses a duplicate without --replace-existing.
        dup = _run(tmp_path, "build", "0.2.0", "--target-file", "CHANGELOG.md")
        assert dup.exit_code != 0

    def test_build_version_all_is_usage_error(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        result = _run(tmp_path, "build", "0.2.0", "--all")
        assert result.exit_code != 0
        msg = _human_error(result).lower()
        assert "all" in msg

    def test_full_build_orders_newest_first_after_unreleased(
        self, tmp_path: Path
    ) -> None:
        self._seed_two_releases(tmp_path)
        result = _run(tmp_path, "build")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        # Headings should be: # Changelog, ## [Unreleased], ## [0.2.0], ## [0.1.0]
        headings = [line for line in text.splitlines() if line.startswith("## ")]
        assert headings == [
            "## [Unreleased]",
            "## [0.2.0] - 2026-02-20",
            "## [0.1.0] - 2026-01-10",
        ]

    def test_full_build_preserves_unreleased_body_by_default(
        self, tmp_path: Path
    ) -> None:
        self._seed_two_releases(tmp_path)
        (tmp_path / "CHANGELOG.md").write_text(
            "# Changelog\n\n## [Unreleased]\n\n- Pending work item\n\n"
        )
        result = _run(tmp_path, "build")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        unreleased_idx = text.index("## [Unreleased]")
        after = text[unreleased_idx:]
        assert "- Pending work item" in after
        # The unreleased body comes before the first release section heading.
        first_release_idx = after.index("## [0.2.0]")
        assert after.index("- Pending work item") < first_release_idx

    def test_no_preserve_unreleased_clears_body(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        (tmp_path / "CHANGELOG.md").write_text(
            "# Changelog\n\n## [Unreleased]\n\n- Pending work item\n\n"
        )
        result = _run(tmp_path, "build", "--no-preserve-unreleased")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        assert "- Pending work item" not in text
        # Unreleased section still present (empty body).
        assert "## [Unreleased]" in text

    def test_full_build_excludes_planned_and_canceled(self, tmp_path: Path) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(tmp_path)
        _seed_release(
            tmp_path, "0.1.0", released_at="2026-01-10", summary="Released one"
        )
        # A planned (not released) release should be excluded by default.
        result = _run(tmp_path, "release", "create", "0.2.0")
        assert result.exit_code == 0, _human_error(result)
        _run(tmp_path, "entry", "add", "0.2.0", "--kind", "added", "--summary", "Planned two")  # noqa: E501
        # A canceled release should be excluded by default.
        result = _run(
            tmp_path,
            "release",
            "tag",
            "0.3.0",
            "--released-at",
            "2026-03-01",
        )
        assert result.exit_code == 0, _human_error(result)
        cancel = _run(  # noqa: E501
            tmp_path,
            "release",
            "cancel",
            "0.3.0",
            "--reason",
            "abandoned",
            "--force-released-unshipped",
        )
        assert cancel.exit_code == 0, _human_error(cancel)

        result = _run(tmp_path, "build")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        assert "## [0.1.0]" in text
        assert "## [0.2.0]" not in text
        assert "## [0.3.0]" not in text

    def test_include_release_status_overrides_default(self, tmp_path: Path) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(tmp_path)
        _seed_release(
            tmp_path, "0.1.0", released_at="2026-01-10", summary="Released one"
        )
        # Create a candidate/planned release with an entry.
        result = _run(tmp_path, "release", "create", "0.2.0")
        assert result.exit_code == 0, _human_error(result)
        _run(tmp_path, "entry", "add", "0.2.0", "--kind", "added", "--summary", "Planned two")  # noqa: E501

        # Default excludes the planned release.
        default = _run(tmp_path, "build", "--dry-run")
        assert default.exit_code == 0, _human_error(default)
        assert "## [0.2.0]" not in default.stdout

        # Explicitly including 'planned' surfaces it.
        included = _run(
            tmp_path, "build", "--dry-run", "--include-release-status", "planned"
        )
        assert included.exit_code == 0, _human_error(included)
        assert "## [0.2.0]" in included.stdout

    def test_full_build_hides_internal_by_default_and_includes_with_flag(
        self, tmp_path: Path
    ) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(tmp_path)
        _seed_release(
            tmp_path,
            "0.1.0",
            released_at="2026-01-10",
            summary="Public feature",
            kind="added",
        )
        _seed_release(
            tmp_path,
            "0.2.0",
            released_at="2026-02-20",
            summary="Internal refactor",
            kind="internal",
            internal=True,
            previous="0.1.0",
        )
        # 0.1.0 has a public entry; 0.2.0 only an internal entry.
        default = _run(tmp_path, "build", "--dry-run")
        assert default.exit_code == 0, _human_error(default)
        assert "Public feature" in default.stdout
        assert "Internal refactor" not in default.stdout

        with_internal = _run(tmp_path, "build", "--dry-run", "--include-internal")
        assert with_internal.exit_code == 0, _human_error(with_internal)
        assert "Internal refactor" in with_internal.stdout

    def test_strict_fails_when_no_date(self, tmp_path: Path) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(tmp_path)
        # A released release with no date: create planned then set status.
        result = _run(tmp_path, "release", "create", "0.1.0")
        assert result.exit_code == 0, _human_error(result)
        result = _run(tmp_path, "release", "update", "0.1.0", "--status", "released")
        assert result.exit_code == 0, _human_error(result)
        _run(tmp_path, "entry", "add", "0.1.0", "--kind", "added", "--summary", "Feature")  # noqa: E501
        strict = _run(tmp_path, "build", "--strict")
        assert strict.exit_code != 0
        assert "date" in _human_error(strict).lower()

    def test_strict_fails_when_no_entries(self, tmp_path: Path) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(tmp_path)
        result = _run(
            tmp_path, "release", "tag", "0.1.0", "--released-at", "2026-01-10"
        )
        assert result.exit_code == 0, _human_error(result)
        strict = _run(tmp_path, "build", "--strict")
        assert strict.exit_code != 0
        assert "entry" in _human_error(strict).lower()
        # --allow-empty unblocks it.
        ok = _run(tmp_path, "build", "--strict", "--allow-empty")
        assert ok.exit_code == 0, _human_error(ok)

    def test_full_build_writes_exactly_one_final_newline(
        self, tmp_path: Path
    ) -> None:
        self._seed_two_releases(tmp_path)
        result = _run(tmp_path, "build")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        assert text.endswith("\n")
        assert not text.endswith("\n\n")

    def test_full_build_json_payload_fields(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        payload = _json(_jrun(tmp_path, "build"))
        assert payload["command"] == "build"
        assert payload["result_type"] == "changelog_full_build"
        result = payload["result"]
        assert isinstance(result, dict)
        for key in (
            "release_count",
            "versions",
            "target_file",
            "updated",
            "dry_run",
            "included_internal",
            "included_statuses",
            "included_release_statuses",
        ):
            assert key in result, f"missing {key}"
        assert result["release_count"] == 2
        assert result["versions"] == ["0.2.0", "0.1.0"]
        assert result["updated"] is True
        assert result["dry_run"] is False
        assert result["included_internal"] is False
        assert result["included_statuses"] == ["accepted"]
        assert "released" in result["included_release_statuses"]

    def test_link_refs_regenerated_deterministically(self, tmp_path: Path) -> None:
        _init_project(tmp_path)
        _write_keepachangelog_config(
            tmp_path, repository_url="https://example.com/owner/repo"
        )
        _seed_release(
            tmp_path, "0.1.0", released_at="2026-01-10", summary="First"
        )
        _seed_release(
            tmp_path,
            "0.2.0",
            released_at="2026-02-20",
            summary="Second",
            previous="0.1.0",
        )
        result = _run(tmp_path, "build")
        assert result.exit_code == 0, _human_error(result)
        text = (tmp_path / "CHANGELOG.md").read_text()
        assert "[Unreleased]: https://example.com/owner/repo/compare/v0.2.0...HEAD" in text  # noqa: E501
        assert "[0.2.0]: https://example.com/owner/repo/compare/v0.1.0...v0.2.0" in text
        assert "[0.1.0]: https://example.com/owner/repo/releases/tag/v0.1.0" in text

    def test_full_build_dry_run_does_not_write(self, tmp_path: Path) -> None:
        self._seed_two_releases(tmp_path)
        result = _run(tmp_path, "build", "--dry-run")
        assert result.exit_code == 0, _human_error(result)
        assert not (tmp_path / "CHANGELOG.md").exists()
        assert "## [0.2.0]" in result.stdout
