"""Generate the command reference from the runtime command inventory."""

from __future__ import annotations

from pathlib import Path

from releaseledger.command_registry import COMMAND_INVENTORY


def render() -> str:
    lines = [
        "# Generated CLI Reference",
        "",
        "<!-- Generated by scripts/generate_cli_reference.py; do not edit. -->",
        "",
        "| Command | Effect | Stability | Aliases |",
        "| --- | --- | --- | --- |",
    ]
    for command in COMMAND_INVENTORY.entries:
        aliases = ", ".join(command.aliases) or "—"
        lines.append(
            f"| `{command.path}` | {command.effect} | {command.stability} | {aliases} |"
        )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    output = Path("docs/commands.generated.md")
    output.write_text(render(), encoding="utf-8")
    print(output)
